# Run commitlint on the commit messages in a pull request.

name: Lint Commit Messages

on:
  - pull_request

jobs:
  commitlint:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: remove tsconfig.json # see issue https://github.com/conventional-changelog/commitlint/issues/3256
        run: |
          rm tsconfig.json
      - name: Check commits
        uses: wagoid/commitlint-github-action@v5
