name: Sync alpha with master
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Create Pull Request
        id: cpr
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_BRANCH: master
          TO_BRANCH: alpha
      - name: Auto-approve pull request for dependent project usages
        uses: hmarr/auto-approve-action@v2
        with:
          pull-request-number: ${{ steps.cpr.outputs.PULL_REQUEST_NUMBER }}
          github-token: ${{ secrets.requirements_bot_github_token }}
      - name: Enable Pull Request Automerge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.PULL_REQUEST_NUMBER }}
          token: ${{ secrets.requirements_bot_github_token }}
